# Generated by Django 6.0.2 on 2026-02-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('video', models.FileField(upload_to='videos/')),
                ('tag', models.CharField(max_length=100)),
                ('views_count', models.PositiveIntegerField(default=1)),
                ('author', models.CharField(default='Sobirjonova Z.', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
