# Generated by Django 6.0.2 on 2026-02-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='like',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
