# Generated by Django 5.2.1 on 2026-01-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='time_to_read',
        ),
        migrations.AddField(
            model_name='news',
            name='time_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
