# Generated by Django 6.0.6 on 2026-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('famale', 'Ayol')])),
                ('photo', models.ImageField(upload_to='person_photos/')),
                ('adress', models.TextField()),
                ('job', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('status', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
