# Generated by Django 6.0.1 on 2026-01-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('photo', models.ImageField(upload_to='category_photo', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('have', 'Sotuvda'), ('have_not', 'Sotuvda emas')], default='have', max_length=10, verbose_name='Holati')),
            ],
        ),
        migrations.CreateModel(
            name='QR_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('url', models.URLField(verbose_name='Sayt manzili')),
                ('photo', models.ImageField(upload_to='qr_codes', verbose_name='QR code')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('photo', models.ImageField(upload_to='meal_photo', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tarif')),
                ('price', models.PositiveIntegerField(verbose_name='Narx')),
                ('weight', models.CharField(max_length=255, verbose_name="Og'irlik/Litr/Portsia")),
                ('status', models.CharField(choices=[('have', 'Sotuvda'), ('have_not', 'Sotuvda emas')], default='have', max_length=10, verbose_name='Holati')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mainapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('price', models.PositiveIntegerField(verbose_name='Narx')),
                ('status', models.CharField(choices=[('have', 'Sotuvda'), ('have_not', 'Sotuvda emas')], default='have', max_length=10, verbose_name='Holati')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='mainapp.meal', verbose_name='Taom')),
            ],
        ),
    ]
