# Generated by Django 6.0.6 on 2026-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoti', models.CharField()),
                ('rasm', models.ImageField(upload_to='')),
                ('laqabi', models.CharField()),
                ('yoshi', models.CharField()),
                ('jinsi', models.CharField(choices=[('boy', "O'g'il bola"), ('girl', 'Qiz bola')])),
                ('sogligi', models.CharField()),
                ('manzil', models.CharField()),
                ('narxi', models.CharField()),
                ('telegram', models.CharField()),
                ('telefon', models.CharField()),
                ('lotok', models.CharField(choices=[('yes', 'Ha biladi'), ('no', "Yo'q bilmaydi")])),
                ('created_on', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
