# Generated by Django 6.0.5 on 2026-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('news_type', models.CharField()),
                ('views_count', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('author', models.CharField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
