# Generated by Django 6.0 on 2025-12-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/category_photos')),
                ('cretaed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ended', 'Sotuvda tugagan'), ('have', 'Sotuvda'), ('arxive', 'Sotuvdan olib tashlangan')], default='have', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('body', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='photos/cake_photos')),
                ('cretaed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ended', 'Sotuvda tugagan'), ('have', 'Sotuvda'), ('arxive', 'Sotuvdan olib tashlangan')], default='have', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
    ]
