# Generated by Django 6.0 on 2025-12-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='photos/news_photos')),
                ('cretaed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ended', 'Sotuvda tugagan'), ('have', 'Sotuvda'), ('arxive', 'Sotuvdan olib tashlangan')], default='have', max_length=50)),
            ],
        ),
    ]
