# Generated by Django 6.0.2 on 2026-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('author', models.CharField(default='Q. Abdurahmon', max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('video', models.FileField(upload_to='videos/')),
                ('views_count', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('creted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
