# Generated by Django 6.0.2 on 2026-02-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='creted_on',
            new_name='created_on',
        ),
    ]
